### ISSUE TITLE
Spotify player playback error: Fatal signal 11 (SIGSEGV) [Ref: #96]

### ISSUE THREAD

**Issue by ssaxena0891** [spotify/android-sdk#182]
I am still getting the error "A/libc﹕ Fatal signal 11 (SIGSEGV) at 0xff5a5378 (code=1), thread 26725" in Android SDK beta 11. The crash is random, it happens after skipping through several songs.

Here is my stack trace:
01-15 01:50:02.975 8928-8928/? A/libc﹕ Fatal signal 11 (SIGSEGV) at 0xb8fbf072 (code=1), thread 8928
01-15 01:50:02.975 8928-10996/? I/SpotifySDK﹕ Got notification: Track changed
01-15 01:50:02.975 8928-10996/? I/SpotifySDK﹕ Got notification: Track ended
01-15 01:50:02.975 8928-10996/? I/SpotifySDK﹕ Got notification: Track started

**Comment by ckoessler** [comment]
Same problem here with SDK beta12 on Nexus 6 running 6.0.1:

> DEBUG   : Build fingerprint: 'google/shamu/shamu:6.0.1/MMB29S/...'
> DEBUG   : Revision: '0'
> DEBUG   : ABI: 'arm'
> DEBUG   : pid: 24512, tid: 24683, name: SpotifySdkPlaye  >>> com.app <<<
> DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc614564c
> DEBUG   :     r0 00000004  r1 934b3ae8  r2 00000004  r3 318c6300
> DEBUG   :     r4 0000000b  r5 934b3b20  r6 9487f34c  r7 9487f3e7
> DEBUG   :     r8 8e7ca17c  r9 9487f34c  sl 00000000  fp 934b42cc
> DEBUG   :     ip 948845cc  sp 934b3a90  lr 948561fc  pc 94859ad8  cpsr 800f0010
> DEBUG   : 
> DEBUG   : backtrace:
> DEBUG   :     #00 pc 0000dad8  /data/app/com.app/lib/arm/libspotify_embedded_shared.so
> DEBUG   :     #01 pc 0000a1f8  /data/app/com.ap/lib/arm/libspotify_embedded_shared.so
> W debuggerd: type=1400 audit(0.0:40): avc: denied { read } for name="kgsl-3d0" dev="tmpfs" ino=8906 > scontext=u:r:debuggerd:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file permissive=0
> I AudioFlinger: BUFFER TIMEOUT: remove(4097) from active list on thread 0xb3e40000
> W ActivityManager:   Force finishing activity com.app/com.app.MainActivity

**Comment by kaaes** [comment]
Thanks for the reports. We'll look into this. If you have a reliable way to reproduce this issue please share them here, it would be a great help.

**Comment by kaaes** [comment]
@ckoessler @ssaxena0891 do you have a way to reproduce this crash?

Some question that could help us debug this:
* What context is playing? (playlist, track, list of tracks - uri(s) would be great)
* What country is the Spotify account registered for?
* Is the app using cache? (it's enabled by default so if it's not turned off it means it's there)
* If the crash happens at skip when does the skip take place? (beginning of the song, middle, end). Is this only during manual skip or when the song finishes on its own?
* Is shuffle or repeat on?
* Is the phone on wifi or 3g when this happens?

**Comment by ckoessler** [comment]
@kaaes I looked at it again today and it seems that I had a memory leak while loading the album art. Now that I fixed that, the crash seems to be gone. I will update on this thread if I see it again.

**Comment by ssaxena0891** [comment]
@kaaes In my case it doesn't look like error in my code, as when I am using Android's default ExoPlayer with the same code, everything is working fine.

Here are the answers of your questions:
1. What context is playing? 
Ans. I am playing tracks using its uri.
My code for this: mPlayer.play("spotify:track:" + trackUrl);

2. What country is the Spotify account registered for?
Ans. UK

3. Is the app using cache?
Ans. No.

4. If the crash happens at skip when does the skip take place? (beginning of the song, middle, end). Is this only during manual skip or when the song finishes on its own?
Ans. At the beginning of song. I noticed it only during manual skip.

5. Is shuffle or repeat on?
Ans. No.

6. Is the phone on wifi or 3g when this happens?
Ans. Currently I tested it on wifi.

**Comment by stefannilsson** [comment]
Any updates on this? I'm experiencing the same issues.

**Comment by lghamie** [comment]
same here.

**Comment by alliejc** [comment]
I am experiencing the same issue.

**Comment by alliejc** [comment]
I am having the same issue. It occurs most predictably when skipping through songs, yet it has also happened on clicking the first song after login.

Moto X Pure Edition
Android Version 6.0

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa3b93196 in tid 24884
A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x36f6a34c in tid 25885

What context is playing? 
-- From any playlist in my account
What country is the Spotify account registered for? 
-- USA
Is the app using cache? 
-- Crashes with cache enabled and disabled
If the crash happens at skip when does the skip take place? (beginning of the song, middle, end). Is this only during manual skip or when the song finishes on its own? 
-- Generally on clicking the "skip" button, but it has also occurred on clicking the first song to play
Is shuffle or repeat on? 
-- No
Is the phone on wifi or 3g when this happens? 
-- Crashes on both

**Comment by tisalmin** [comment]
@kaaes, our experiences of the crash (issue #214):

What context is playing? (playlist, track, list of tracks - uri(s) would be great)
- No pattern found with specific lists or tracks

What country is the Spotify account registered for?
- Finland

Is the app using cache? (it's enabled by default so if it's not turned off it means it's there)
- Yes

If the crash happens at skip when does the skip take place? (beginning of the song, middle, end). Is this only during manual skip or when the song finishes on its own?
- This happens with both cases. However, it seems that it is always comes to starting the playback of a new song.

Is shuffle or repeat on?
- No

Is the phone on wifi or 3g when this happens?
- It seems this happens more frequent on 3G/4G connections (or a weak network in general)

Other guesses: we see this issue also in long term testing. Perhaps when the token is expired? Just a guess.

**Comment by d-kunin** [comment]
Hello folks, that most likely was fixed in the latest release https://github.com/spotify/android-sdk/releases/tag/1.0.0-beta13 please check!

**Comment by alliejc** [comment]
@d-kunin @kaaes I updated to beta13 and still experiences the same error.

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xbcd612e in tid 13509 (SpotifySdkPlaye)

**Comment by tisalmin** [comment]
Looks like we have the same issue. I haven't been able to get the trace yet, but have seen crashes in similar situations. Will dig some more...

**Comment by tisalmin** [comment]
I can confirm the **crashes with both cache enabled and disabled**. I still somehow feel this happens more often on cell network, when the network is not at its best.

---
07-17 16:15:58.017 20406-20406/com.ficonic.project W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.ficonic.project/files
07-17 16:15:58.032 20406-24853/com.ficonic.project D/SpotifySDK: Setting playback bitrate to: 1
07-17 16:15:58.032 20406-24853/com.ficonic.project D/SpotifySDK: Use diskcache: false
07-17 16:15:58.032 20406-24853/com.ficonic.project W/art: Attempt to remove local handle scope entry from IRT, ignoring
07-17 16:15:59.247 20406-24853/com.ficonic.project I/SpotifySDK: Got notification: Became active playing device
07-17 16:15:59.247 20406-24853/com.ficonic.project I/SpotifySDK: playbackCallbackOnSeek (to 0ms)
07-17 16:15:59.257 20406-20406/com.ficonic.project D/SpotifyPlayer: PlaybackEvent -- BECAME_ACTIVE
07-17 16:16:03.282 20406-24853/com.ficonic.project I/SpotifySDK: Login complete
07-17 16:16:03.347 20406-24853/com.ficonic.project I/SpotifySDK: Got notification: Track changed
07-17 16:16:03.347 20406-24853/com.ficonic.project I/SpotifySDK: Got notification: Play
07-17 16:16:03.352 20406-24853/com.ficonic.project I/SpotifySDK: Got notification: Track started
07-17 16:16:03.352 20406-20406/com.ficonic.project A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe50cb377 in tid 20406 (conic.project)
---
07-17 18:19:27.517 3194-5628/com.ficonic.project I/SpotifyTokenManager: time left (min): 17
07-17 18:19:27.577 3194-3194/com.ficonic.project W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.ficonic.project/files
07-17 18:19:27.597 3194-5631/com.ficonic.project D/SpotifySDK: Setting playback bitrate to: 1
07-17 18:19:27.597 3194-5631/com.ficonic.project D/SpotifySDK: Use diskcache: true
07-17 18:19:27.597 3194-5631/com.ficonic.project W/art: Attempt to remove local handle scope entry from IRT, ignoring
07-17 18:19:27.982 3194-5631/com.ficonic.project I/SpotifySDK: Got notification: Became active playing device
07-17 18:19:27.982 3194-5631/com.ficonic.project I/SpotifySDK: playbackCallbackOnSeek (to 0ms)
07-17 18:19:27.992 3194-5631/com.ficonic.project I/SpotifySDK: Got notification: Track changed
07-17 18:19:27.992 3194-5631/com.ficonic.project I/SpotifySDK: Got notification: Play
07-17 18:19:27.997 3194-3194/com.ficonic.project D/SpotifyPlayer: PlaybackEvent -- BECAME_ACTIVE
07-17 18:19:27.997 3194-5631/com.ficonic.project I/SpotifySDK: Got notification: Track started
07-17 18:19:27.997 3194-5631/com.ficonic.project A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x245d734b in tid 5631 (SpotifySdkPlaye)
---

**Comment by alliejc** [comment]
Unfortunately, still experiencing the same error

**Comment by sampurcell93** [comment]
@alliejc are you having this error even with beta23-noconnect?
