### ISSUE TITLE
How to get current position of track repeatedly?

### ISSUE THREAD

**Issue by sampurcell93** [spotify/android-sdk#283]
Hi, I just switched over from beta13 to beta22b. I have some code that runs in a loop and gets the current playback position:

```
private ScheduledExecutorService timeUpdateService = Executors.newSingleThreadScheduledExecutor();
scrubber = timeUpdateService.scheduleWithFixedDelay(
      new Runnable(){
        @Override
        public void run() {
          if (mPlayer != null) 
              PlaybackState state = mPlayer.getPlaybackState(); 
              emitPosition(state.positionMs)
          }
      }, 0, 100, TimeUnit.MILLISECONDS);
```

Unfortunately, since switching to 22b, the value of `state.positionMs` is always the same until a PlayerEvent is received. So when I pause and resume the song, the positionMs will be updated to the correct value - but then stop updating immediately. Is there any way to trigger an update of this value, or a better way to poll the playerstate for position? Thanks!

**Comment by tcrondo** [comment]
I have the same problem. In beta22, thanks to the dev team, I can know the seek completion by giving `Player.OperationCallback` to `Player.seekTo()`, but as @sampurcell93 says, the playback position returned by `Player.getPlaybackState()` is not up-to-date even after seek completion.
```
player.seekTo(new Player.OperationCallback() {
  @Override void onSuccess() {
    PlaybackState state = player.getPlaybackState();
    update(state.positionMs); // <- this is not up-to-date, remains the same as before seeking
  }
  @Override void onError(Error error) {...}
}, position);
```
I have to keep track of playback position on my own until `PlayerEvent` is notified.

**Comment by d-kunin** [comment]
Thanks for reporting this, there is no way to force-update position, but we take care of it in the next release.

**Comment by d-kunin** [comment]
Fixed in beta 23

**Comment by sampurcell93** [comment]
Dope! Thanks for the quick work, guys.

**Comment by tcrondo** [comment]
Thank you for the update. I tried beta23, but I still can't get the up-to-date playback position after seeking in the callback. Am I wrong to update playback states from within the callbacks?
