### ISSUE TITLE
Temporary connection error occurred

### ISSUE THREAD

**Issue by Wolftein** [spotify/android-sdk#77]
My console is spaming Temporary connection error occurred when trying to play a song. I've checked my internet and app's permission (INTERNET permission is on my android manifest).

**Comment by Wolftein** [comment]
Oh, my ISP was having problems with spotify's backend.

**Comment by kaaes** [comment]
We had some issues with connectivity in mobile SDKs today but this has been fixed now.

**Comment by Wolftein** [comment]
I'm still getting some 'Temporary connection error', but after 10 or 15 it starts playing the track.

**Comment by kaaes** [comment]
@Wolftein that shouldn't be happening anymore. Are you still having issues?

**Comment by krunal131987** [comment]
I also have an issue with Temporary connection error but player is working

**Comment by Wolftein** [comment]
Not happening anymore :)
